name: notifybear_api_test
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase dependencies
  firebase_core: ^2.13.1
  firebase_auth: ^4.9.0

  # Google Sign-In dependency
  google_sign_in: ^6.1.3

  # HTTP dependency for API requests
  http: ^1.2.1

  # Cupertino Icons for iOS style icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting package
  flutter_lints: ^3.0.0

flutter:
  # Ensures Material Icons font is included
  uses-material-design: true

  # Add assets here
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Custom fonts can be added here
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
